{
 "title": "Accusys - Uniweb2 [Prometheus]",
 "description": "【English version】Update 2020.10.10, add the overall resource overview! Support Grafana6&7,Support Node Exporter v0.16 and above.Optimize the main metrics display. Includes: CPU, memory, disk IO, network, temperature and other monitoring metrics。https://github.com/starsliao/Prometheus",
 "tags": [
  "Prometheus",
  "node_exporter",
  "StarsL.cn",
  "Accusys",
  "Uniweb",
  "Unimep"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cliente", "label": "Cliente", "query": { "query": "label_values(cliente)" } },
   {
    "name": "entorno",
    "label": "Entorno",
    "query": {
     "query": "label_values({cliente=~\"$cliente\"}, entorno)"
    }
   },
   {
    "name": "srvhostname",
    "label": "Servidor",
    "query": {
     "query": "label_values({cliente=~\"$cliente\",entorno=~\"$entorno\"}, srvhostname)"
    }
   },
   {
    "name": "device",
    "label": "NIC",
    "query": {
     "query": "label_values(node_network_info{cliente=~\"$cliente\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"},instance)"
    }
   },
   {
    "name": "maxmount",
    "label": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{cliente=~\"$cliente\",instance=~'$node',fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{cliente=~\"$cliente\",entorno=~\"$entorno\"}))"
    }
   },
   { "name": "interval", "label": "Interval", "query": "15s,30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "General - $cliente | $entorno | $srvhostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "OK",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"})"
    }
   ]
  },
  {
   "title": "CPU - % uso",
   "type": "gauge",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU Busy"
    }
   ]
  },
  {
   "title": "Memoria - % uso",
   "type": "gauge",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",} / (node_memory_MemTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",})))* 100",
     "legendFormat": "Used RAM Memory"
    }
   ]
  },
  {
   "title": "/ - % uso",
   "type": "gauge",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"}-node_filesystem_free_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"})*100 /(node_filesystem_avail_bytes {cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"}+(node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"}-node_filesystem_free_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"}))",
     "legendFormat": "Used RAM Memory"
    }
   ]
  },
  {
   "title": "Contenedores - uso de CPU en $srvhostname",
   "type": "timeseries",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",image!=\"\"}[1m])) by (id,name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Contenedores - corriendo",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Temperatura del hardware",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}"
    }
   ]
  },
  {
   "title": "CPU - Cores",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\", mode='system'})"
    }
   ]
  },
  {
   "title": "Memoria - uso",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"} - node_memory_MemAvailable_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "/ - uso",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mountpoint=\"/\"} - node_filesystem_avail_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SWAP - % uso",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"} + 1)/ (node_memory_SwapTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"} + 1))) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "CPU - carga 5",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_load5{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}"
    }
   ]
  },
  {
   "title": "Memoria - total",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "/ - total",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mountpoint=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Contenedores - salud en $srvhostname",
   "type": "table",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "container_state_health_status{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}"
    }
   ]
  },
  {
   "title": "Contenedores - uso de memoria en $srvhostname",
   "type": "timeseries",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Detalles del servidor：$srvhostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU - carga"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"} / (node_memory_MemTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"})))* 100",
     "legendFormat": "Memoria - uso"
    },
    {
     "expr": "(node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"}-node_filesystem_free_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"})*100 /(node_filesystem_avail_bytes {cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"}+(node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"}-node_filesystem_free_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint=\"/\"}))",
     "legendFormat": "/ - uso"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"} + 1)/ (node_memory_SwapTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"} + 1))) * 100",
     "legendFormat": "SWAP - uso"
    }
   ]
  },
  {
   "title": "Discos (EXTx/XFS) en $srvhostname",
   "type": "table",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "(node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Memoria - total",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU - cores",
   "type": "stat",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\", mode='system'})"
    }
   ]
  },
  {
   "title": "CPU - utilizado en $srvhostname",
   "type": "timeseries",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mode=\"system\"}[$__rate_interval])) by (cliente, entorno, srvhostname) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mode=\"user\"}[$__rate_interval])) by (cliente, entorno, srvhostname) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mode=\"iowait\"}[$__rate_interval])) by (cliente, entorno, srvhostname) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",mode=\"idle\"}[$__rate_interval])) by (cliente, entorno, srvhostname))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "memoria - utilizado en $srvhostname",
   "type": "timeseries",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"} - node_memory_MemAvailable_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}",
     "legendFormat": "Avaliable"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"} / (node_memory_MemTotal_bytes{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"})))* 100",
     "legendFormat": "Used%"
    }
   ]
  },
  {
   "title": "RED - tráfico en $srvhostname",
   "type": "timeseries",
   "description": "$cliente $entorno $srvhostname",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",id=\"/\"}[30s])) by (id, cliente, entorno, srvhostname)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\",id=\"/\"}[30s])) by (id, cliente, entorno, srvhostname)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "CPU - carga en $srvhostname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\"}",
     "legendFormat": "15m"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{cliente=~\"$cliente\",entorno=~\"$entorno\",srvhostname=~\"$srvhostname\", mode='system'}) by (cpu,srvhostname)) by(srvhostname)",
     "legendFormat": "CPU cores"
    }
   ]
  }
 ]
}