# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: prometheus
    orgId: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: prometheus
    # <string, required> Sets the data source type.
    type: prometheus
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: prometheus
    # <string> Sets the data source's URL, including the
    # port.
    url: http://prometheus-master:9091
    # for new panels. You can set only one default
    # data source per organization.
    isDefault: 1
    version: 1
    # <bool> Allows users to edit data sources from the
    # Grafana UI.
    editable: false


  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: loki
    # <string, required> Sets the data source type.
    type: loki
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: po2i3u5
    # <string> Sets the data source's URL, including the
    # port.
    url: http://loki-master:3100
    # for new panels. You can set only one default
    # data source per organization.
    isDefault: 0
    version: 1
    # <bool> Allows users to edit data sources from the
    # Grafana UI.
    editable: false