apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  url: http://prometheus-master:9090
  isDefault: 1
  version: 1
  editable: false
- name: loki
  type: loki
  access: proxy
  url: http://loki-master:3100
  isDefault: 0
  version: 1
  editable: false