version: "3.7"

volumes:
  grafana-master-data:
  prometheus-master-data:    
  loki-master-data:

services:
  grafana-master:
    image: grafana/grafana:9.3.4
    container_name: grafana-master
    restart: unless-stopped
    volumes:
    - grafana-master-data:/var/lib/grafana
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    ports:
    - 3000:3000

  prometheus-master:
    image: prom/prometheus:v2.28.1
    container_name: prometheus-master
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-master-data:/prometheus
    ports:
    - 9091:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=1y'
    - '--web.enable-lifecycle'

  loki-master:
    image: grafana/loki:2.0.0
    container_name: loki-master
    restart: unless-stopped
    volumes:
    - ./loki-config.yml:/mnt/config/loki-config.yml
    - loki-master-data:/loki
    ports:
    - 3100:3100
    command: 
    - '-config.file=/mnt/config/loki-config.yml'