global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
      labels:

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']
      labels:

  - job_name: 'docker_state_exporter'
    static_configs:
      - targets: ['docker_state_exporter:8080']

  - job_name: 'blackbox'
      metrics_path: /probe
      params:
      module: [http_2xx]  # Look for a HTTP 200 response.
      target_groups:
      - targets:
          - prometheus.io   # Target to probe
          - www.accusys.com.ar
      relabel_configs:
      - source_labels: [__address__]
          regex: (.*)(:80)?
          target_label: __param_target
          replacement: ${1}
      - source_labels: [__param_target]
          regex: (.*)
          target_label: instance
          replacement: ${1}
      - source_labels: []
          regex: .*
          target_label: __address__
          replacement: blackbox_exporter:9115  # Blackbox exporter.