global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
      labels:

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']
      labels:

  - job_name: 'docker_state_exporter'
    static_configs:
      - targets: ['docker_state_exporter:8080']

  - job_name: 'blackbox'
    static_configs:
      - targets: ['blackbox_exporter:9115']